---
name: Update Doc Version

# yamllint disable-line rule:truthy
on:
  # this is the trigger that really does the work
  push:
    tags:
      - v*
  # pull_request is only here to check the behaviour without needing to merge
  # all the time
  pull_request:
    branches:
      - main

jobs:
  readme-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        uses: fregante/setup-git-user@v2

      # we use ourself to get the information for the release
      - name: Get Change Info
        uses: chizovation/changesets-changelog-info@v0.1.5
        id: get-changelog-info

      - name: Prepare Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Bumpversion deps
        shell: bash
        run: |
          pip install --no-cache-dir -U pip
          pip install --no-cache-dir bumpversion

      - name: Run Bumpversion
        shell: bash
        # yamllint disable rule:line-length
        run: |
          {%raw-%}
          export current_version="${{ steps.get-changelog-info.outputs.last-change-version }}"
          bumpversion --verbose \
            --allow-dirty \
            --no-commit \
            --no-tag \
            --message "chore: update version in files (${current_version})\n\n[skip ci]" \
            --new-version "${current_version}" \
            patch
          {%-endraw%}
        # yamllint enable rule:line-length

      - name: Debug Commits and Current Branch
        run: |
          {%raw-%}
          echo "Commits:"
          echo "===================="
          git log --oneline --decorate --graph -n 10
          echo "Current Branch:"
          echo "===================="
          git branch --show-current
          echo "Default Branch:"
          echo "===================="
          echo "${{ github.event.repository.default_branch }}"
          echo "last-change-version"
          echo "===================="
          echo "${{ steps.get-changelog-info.outputs.last-change-version }}"
          echo "git diff"
          echo "===================="
          git diff
          {%-endraw%}

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          # yamllint disable rule:line-length
          title: 'chore: update version in files ({%raw%}${{ steps.get-changelog-info.outputs.last-change-version}}{%endraw%})'
          commit-message: |
            chore: update version in files ({%raw%}${{ steps.get-changelog-info.outputs.last-change-version}}{%endraw%})

            [skip ci]'
          base: '{%raw%}${{ github.event.repository.default_branch }}{%endraw%}'
          delete-branch: true
          token: '{%raw%}${{ secrets.CHANGESETS_TOKEN }}{%endraw%}'
          # yamllint enable rule:line-length

      - uses: peter-evans/enable-pull-request-automerge@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          # yamllint disable rule:line-length
          token: '{%raw%}${{ secrets.CHANGESETS_TOKEN }}{%endraw%}'
          pull-request-number: '{%raw%}${{ steps.create-pr.outputs.pull-request-number }}{%endraw%}'
          # yamllint enable rule:line-length
