---
# .github/workflows/auto-author-assign.yml
name: PR Owner

# yamllint disable-line rule:truthy
on:
  - pull_request

permissions:
  pull-requests: write

jobs:
  assign-author:
    name: Assign Author
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
